### ISSUE TITLE
Implementar socket para conexão com Servidor na classe UserInstance (R1)

### ISSUE THREAD

**Issue by prosperor** [prosperor/ForcaMultiplayer#1]
* Cliente: é o programa que cada jogador rodará em seu próprio computador. Esse programa recebe o endereço IP do servidor como argumento de configuração, e se conecta a ele.

O cliente deve saber previamente o endereço do servidor (IP) ou seu nome (hostname) e a porta
 
Consultar: https://github.com/prosperor/ForcaMultiplayer/wiki/Links-%C3%BAteis

**Comment by FabioFernandesCosta** [comment]
Implementado aos pouco em varios commits, concluindo no commit [comunicação estabelecida
](https://github.com/prosperor/ForcaMultiplayer/commit/567330848c7f65916ec0f120fb10a89dd39c7e00)
