### ISSUE TITLE
Implementar a classe ManipulaTxt (R0.1)

### ISSUE THREAD

**Issue by prosperor** [prosperor/ForcaMultiplayer#7]
Classe deve criar um arquivo padrão com ao menos 2 palavras no arquivo de texto, logo no construtor
A classe deve acessar as palavras via texto, ou seja, não vale criar um List já com as palavras inclusas, e sim o método deve pegar as palavras do txt e inserir na List
As palavras desse arquivo devem ser acessíveis por um método (sugiro que retorne um List com as palavras)

**Comment by FabioFernandesCosta** [comment]
### ManipulaTxt implementado"
commit:
[ManipulaTxt implementado [R0.1]](https://github.com/prosperor/ForcaMultiplayer/commit/dd3d17966f3fa86a2a363fd90a78a8caeb411260)


- No contrutor da classe primeiramente o arquivo dicio.txt que está localizado na pasta src , é lido, linha a linha, a cada linha lida a variavel int iLinhas recebe mais +1 ao seu valor, isso enquanto o valor da linha não for nulo, ao fim, iLinhas tem um valor equivalente ao numero de linhas-1, servindo como index;

- No metodo setPalavra, uma palavra aleatória é escolhida do dicio.txt;

- No metodo getPalavra, a palavra, anteriormente definida pelo setPalavras é retornado;

- O metodo getPalavra é sobrecarregado, se o metodo for chamado sem nenhum parametro, ele apenas retorna a palavra atual, se for chamado contendo um booleano como parametro, ele chama o setPalavra e em seguida retorna a palavra definida.

**Comment by FabioFernandesCosta** [comment]
### ManipulaTxt aprimorado

commit:
[Update ManipulaTxt.java](https://github.com/prosperor/ForcaMultiplayer/commit/37822fab147600f87238b0e11779d16e8846c453l)

- O construtor agora chama o  método setPalavra em seu final

**Comment by prosperor** [comment]
Converter as palavras para UpperCase ou LowerCase pois a entrada do usuário será padronizada a partir disso

**Comment by FabioFernandesCosta** [comment]
[Agora todas as palavras são completamente em lower case](https://github.com/prosperor/ForcaMultiplayer/commit/17757f4866054749b0a3d75163ec18c30d66abb6)
