### ISSUE TITLE
Implementar a classe main UserInstance (R0.3)

### ISSUE THREAD

**Issue by prosperor** [prosperor/ForcaMultiplayer#9]
A classe deve conter os seguintes atributos 

- ID que será recebido no cadastramento (não modificável de maneira nenhuma)
- Nome do usuário (modificável, mas não necessariamente agora)

A classe deve conter 

- Uma sequencia que cadastra o usuário e se comunica com o método da classe Servidor de cadastramento
- Menu

A classe irá se comunicar com a classe Servidor para se conectar ao jogo e enviar requisições e tentativas de chute
A classe fará a interface para cadastrar o usuário no servidor
A classe deverá verificar se o nome do usuário já não existe na classe servidor via ID (futuramente)
A classe deverá montar a visualização estruturada das informações vindas do servidor afim o visual do jogo para o usuário
As requisições feitas a classe servidor sempre irão requerer o ID

**Comment by FabioFernandesCosta** [comment]
precisando no servidor um metodo para entrar como usuario ja existente.
No aguardo para retomada

**Comment by FabioFernandesCosta** [comment]
Verificação de usuario existente feito com o uso de sobrecarga na classe servidor

**Comment by FabioFernandesCosta** [comment]
feito com o commit: [userInstance convertido em main](https://github.com/prosperor/ForcaMultiplayer/commit/9387746a8cdcf496bc740020acde56e9c176a9f4)
